### ISSUE TITLE
[PHP] can't recognize this line

### ISSUE THREAD

**Issue by downuse** [dail8859/DoxyIt#11]
function get_user_name($uid='',$type='username',$key='sub'){

**Comment by dail8859** [comment]
Thanks for the report! You can download the fixed plugin below since it will probably take a while to get this change available through the plugin manager. Just extract it and copy over your current `DoxyIt.dll` file.

[DoxyIt.zip](https://github.com/dail8859/DoxyIt/files/151040/DoxyIt.zip)

**Comment by downuse** [comment]
okay, thank you!
