### ISSUE TITLE
Cannot comment a function on javascript

### ISSUE THREAD

**Issue by farell** [dail8859/DoxyIt#12]
It works fine with the following function declaration:
function Space(a) {
    this.models = {};
	this.handles = {};
	this.reconnectHandle = null;
	this.configure(a);
}

but failed with the following:

Space.prototype.connect = function () {
    this.lnodeClient.connect(this._options.nodeaddr, 
    this._options.nodeid)
}

Error info--> Error:Cannot parse function definition.Make sure the cursor is on the line directly above the function or method definition.

**Comment by dail8859** [comment]
Thanks for the report! Since the Plugin Manager never seems to push updates any more, you can download the fixed version below. Just extract it and copy over your current `DoxyIt.dll` file.

[DoxyIt.zip](https://github.com/dail8859/DoxyIt/files/224615/DoxyIt.zip)

**Comment by farell** [comment]
thanks for the work
