### ISSUE TITLE
$FUNCTION not recognizing function name

### ISSUE THREAD

**Issue by koog1000** [dail8859/DoxyIt#15]
In both python and C the function name returned is an empty string. I haven't looked through this code at all really, but (at least for C) shouldn't the regex be something similar to "\s+\w+\s*[(]" ? Then you can strip the open parenthesis and whitespace to get the function name.

**Comment by dail8859** [comment]
Thanks for opening the issue. The function name was getting parsed but not associated with the `$FUNCTION` keyword correctly. 

You can download a fixed version below:

[DoxyIt.zip](https://github.com/dail8859/DoxyIt/files/968999/DoxyIt.zip)
[DoxyIt_64.zip](https://github.com/dail8859/DoxyIt/files/969000/DoxyIt_64.zip)

**Comment by koog1000** [comment]
Thank you much. Appreciate the fast response.
