### ISSUE TITLE
Add new line after first

### ISSUE THREAD

**Issue by WinterSilence** [dail8859/DoxyIt#16]
I add comment for method:
~~~
/**
 * @return string
 */
private function getLogPath($name = 'error')
{
~~~
and try add line after first line (set cursor after `/**` and press `Enter`):
~~~
/**
 * New line after first line (not work now).
 * @return string
 */
~~~
But plugin add new comment:
~~~
/**
 * 
 */ 
 * @return string
 */
~~~

**Comment by dail8859** [comment]
I have known this existed a while ago. Unfortunately when you start looking at the details it gets messy. I don't have any ideas how to easily handle a situation like this.

**Comment by WinterSilence** [comment]
@dail8859 after docblock added, need remove line with `parser.doc_end`, if next line begin as  `parser.doc_line`.

**Comment by dail8859** [comment]
I've added a commit to fix this. This won't be available to download via the plugin manager until a release is created. Until then you can download the DLL and just copy it over the one you have already:

- 32 bit: https://ci.appveyor.com/project/dail8859/doxyit/build/job/r5vshunxi2xnr15t/artifacts
- 64 bit: https://ci.appveyor.com/project/dail8859/doxyit/build/job/7pkdhp1k8tvs5jud/artifacts

Please note. If you are using 64 bit Notepad++ your existing DLL on your computer will be called "DoxyIt_64.dll" but the one you download is named differently "DoxyIt.dll" so delete the existing one and use this new one.

If you have any problems please let me know.

**Comment by WinterSilence** [comment]
@dail8859 not full fixed
~~~
	/**
	 * Work fine!
	 * Whitespace after *
	 */
~~~
See:
~~~
	/**
	 * Bug :(
	 */
	 *No whitespace after *
	 */
~~~
