### ISSUE TITLE
Add new line after first #16

### ISSUE THREAD

**Issue by WinterSilence** [dail8859/DoxyIt#17]
@dail8859 not full fixed
~~~
	/**
	 * Work fine!
	 * Whitespace after *
	 */
~~~
See:
~~~
	/**
	 * Bug :(
	 */
	 *No whitespace after *
	 */
~~~

**Comment by dail8859** [comment]
Technically it is working as expected since the 2nd line doesn't start with the string you have it configured to use. 

That being said, it may be possible to ignore any whitespace that doesn't match.
