### ISSUE TITLE
Parser fails on C++ operator overloads

### ISSUE THREAD

**Issue by daniel-starke** [dail8859/DoxyIt#18]
Trying to comment a C++ method like
```c++
constexpr inline bool operator!= (const A & o) const {
	return this->value != o.value;
}
```
fails with the error message "Error: Cannot parse function definition. Make sure the cursor is on the line directly above the function or method definition.".

**Comment by dail8859** [comment]
I've made an update that appears to fix this issue. I'm planning on doing a release at some point, but until then you can download this recent build to verify it works for you.

- [32 bit](https://ci.appveyor.com/project/dail8859/doxyit/build/job/7460t924l25sn1t6/artifacts)
- [64 bit](https://ci.appveyor.com/project/dail8859/doxyit/build/job/natk9sxtq6uty3j7/artifacts)

Download one of the DLLs for your version and copy over your existing DoxyIt.dll file. If you are using the 64 bit version your existing file might be called DoxyIt_64.dll but go ahead and replace it with the one you downloaded.

**Comment by daniel-starke** [comment]
Thank you. It is now working as expected.
