### ISSUE TITLE
Parser fails on C++ functions with conditional template instantiation and parameter packs

### ISSUE THREAD

**Issue by daniel-starke** [dail8859/DoxyIt#21]
Trying to comment a C++ function like
```c++
template <size_t i = 0, typename ...Args>
static typename enable_if<i == sizeof...(Args), bool>::type extractArgs(uint8_t * &, size_t &, tuple<Args...> &) {
	return true;
}
```
fails with the error message "Error: Cannot parse function definition. Make sure the cursor is on the line directly above the function or method definition.".

**Comment by dail8859** [comment]
To parse out the function or method name this plugin just uses some pretty simple regular expressions. Handling this complex of syntax would require quite a bit of effort. Unfortunately this capability is probably well outside the scope of what DoxyIt will be able to handle.
