### ISSUE TITLE
Active commenting doesn't trigger

### ISSUE THREAD

**Issue by n21lv** [dail8859/DoxyIt#24]
Whenever I type /** and press [Enter], nothing happens. DoxyIt File/Function work fine. Using NP++ 7.7.1 (64-bit).

**Comment by dail8859** [comment]
@n21lv Thanks for reporting this issue. Until I create another release (which should be "soon") you can try [this DLL](https://ci.appveyor.com/project/dail8859/doxyit/build/job/5x64fhdj6q6ak7aq/artifacts). Just download the DLL and copy over your existing `DoxyIt.dll` file.

If you still have issues after trying this DLL please reopen. Thanks.

**Comment by n21lv** [comment]
Hey, thanks for the response. I've never used AppVeyor, though, so I am not sure if I did all correct. I went to Jobs > "Configuration: Release; Platform: x64" > Artifacts > DoxyIt.dll. Downloaded that and copied over the existing file, restarted NP++ and tried to trigger active commenting by typing /** and hitting [Enter], but nothing happened.  
How do I reopen this?

**Comment by dail8859** [comment]
It appears to be working for me. Can you provide a detailed set of steps to reproduce the issue? Also the debug information of Notepad++ (under the `?` menu)

**Comment by n21lv** [comment]
**Debug info**
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DoxyIt.dll mimeTools.dll NppConverter.dll SurroundSelection.dll

I am not sure about the steps to reproduce, as it seems to be really simple:
1. Open NP++, new file.
2. Type /**, press [Enter]
3. Nothing happens.

Just in case, where should I put the DLL? I have just checked and I actually have two versions: one in <npp_home_dir>\plugins\Doxyit and another one in <npp_home_dir>\plugins

**Comment by n21lv** [comment]
Okay, I got this working. I think I probably downloaded the wrong version of the DLL the last time. I have redownloaded it and replaced the existing one, and now I get the feature trigger working nicely.

**Comment by dail8859** [comment]
> Okay, I got this working. I think I probably downloaded the wrong version of the DLL the last time.

Glad it is working now!

> I am not sure about the steps to reproduce...

Make sure the file's languages is set (unless you have new files set to C/C++, etc by default). Just typing `/**[Enter]` in normal text file will not trigger at all.

**Comment by n21lv** [comment]
I have JS set as default, so that's not the case. Thanks for sharing that
DLL with me again!
