### ISSUE TITLE
Indentation tabs

### ISSUE THREAD

**Issue by Wurstbrotc5** [dail8859/DoxyIt#25]
Hi,

first of all, thank you for this great plugin!

One maybe small issue: The "active comments" (typing /** enter to generate a comment) always use tabs as indentation. Would it be possible to honor the tab/spaces settings from NPP?

Sadly some code receivers (projects, companies, whatever) are very strict about their tab/space preferance.

**Comment by dail8859** [comment]
Thanks for opening the issue.

Everything appears to be working correctly for me using Notepad++ v7.7.1 32-bit and DoxyIt v0.4.3

![comment](https://user-images.githubusercontent.com/3694843/61874497-8dee5b00-aeb6-11e9-9043-c949c30fbab9.gif)

---

You'll have to be a bit more specific on what versions you are using and if you are trying anything different than I tried above. Also you should probably try DoxyIt [v0.4.4](https://github.com/dail8859/DoxyIt/releases/tag/v0.4.4) if you haven't already. I don't think it is available through the Plugin Admin yet.

**Comment by Wurstbrotc5** [comment]
Thank you for the response,

and sorry my description was wrong, the problem is not even the tab/space _setting_.

I realized now that a comment above an existing function whatever indentation the function has in the first line. (Of course existing code is not affected by Notepad++'s settings).

Maybe this comment behaviour even is intentional (?)

In any case, I use Notepad++ 7.7 32bit, and tried Doxyit in both v0.4.3 and 0.4.4 (altough both report as 0.4.3 inside of the program). Temporarily removing all other plugins makes no difference

A screen recording too, with some dummy PHP code, behaving like that for both tab and space settings:

![record](https://user-images.githubusercontent.com/53292913/61984982-37dcfd00-b007-11e9-9a03-5a8aa9f63c37.gif)

**Comment by dail8859** [comment]
> Probably this comment behaviour even is intentional (?)

Yes. It intentionally matches the whitespace of the function definition (even if that whitespace is a mixture of tabs/spaces), regardless of the actual editor setting. Maybe not a great example I put together previous, but you get the point. Also if comment blocks are expanded it keeps whatever whitespace indentation is being used. 

> (altough both report as 0.4.3 inside of the program)

Good catch. That one is my mistake.

**Comment by Wurstbrotc5** [comment]
Ok, then I'll close this.
Thank you for your time
