### ISSUE TITLE
No longer work for JS on Notepad++ 6.8.6

### ISSUE THREAD

**Issue by diegocr** [dail8859/DoxyIt#8]
Hi,

The last Notepad++ version introduced changes on the language detection, which broke the plugin while working with Javascript files.

Taking a look at the latest [Notepad_plus_msgs.h](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L42) we can see they introduced a new `L_JAVASCRIPT` type on the `LangType` enum, so i think it's just a matter of additionally checking for that.

Cheers.

**Comment by dail8859** [comment]
This new release can be downloaded [here](https://github.com/dail8859/DoxyIt/releases/tag/v0.2.7). If you find any other issues, just let me know.

**Comment by diegocr** [comment]
Thank you!
